"""Public reporting export metadata."""

from __future__ import annotations

LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "SEVERITY_ORDER": ("r2morph.reporting.gate_evaluator", "SEVERITY_ORDER"),
    "GateEvaluator": ("r2morph.reporting.gate_evaluator", "GateEvaluator"),
    "GateFailure": ("r2morph.reporting.gate_evaluator", "GateFailure"),
    "FilteredReport": ("r2morph.reporting.report_builder_models", "FilteredReport"),
    "ReportContext": ("r2morph.reporting.report_builder_models", "ReportContext"),
    "_has_structural_risk": ("r2morph.reporting.report_pass_classification", "_has_structural_risk"),
    "_has_symbolic_risk": ("r2morph.reporting.report_pass_classification", "_has_symbolic_risk"),
    "_is_clean_pass": ("r2morph.reporting.report_pass_classification", "_is_clean_pass"),
    "_is_covered_pass": ("r2morph.reporting.report_pass_classification", "_is_covered_pass"),
    "_is_risky_pass": ("r2morph.reporting.report_pass_classification", "_is_risky_pass"),
    "_is_uncovered_pass": ("r2morph.reporting.report_pass_classification", "_is_uncovered_pass"),
    "_normalized_pass_map": ("r2morph.reporting.report_helpers", "_normalized_pass_map"),
    "_summary_first": ("r2morph.reporting.report_helpers", "_summary_first"),
    "resolve_general_symbolic_state": (
        "r2morph.reporting.report_state",
        "resolve_general_symbolic_state",
    ),
    "resolve_mismatch_view": ("r2morph.reporting.report_state", "resolve_mismatch_view"),
    "resolve_pass_filter_sets": ("r2morph.reporting.report_state", "resolve_pass_filter_sets"),
    "_first_available": ("r2morph.reporting.report_view_selection", "_first_available"),
    "MutationResult": ("r2morph.reporting.sarif_formatter", "MutationResult"),
    "ReportData": ("r2morph.reporting.sarif_formatter", "ReportData"),
    "SARIFFormatter": ("r2morph.reporting.sarif_formatter", "SARIFFormatter"),
    "ValidationResult": ("r2morph.reporting.sarif_formatter", "ValidationResult"),
    "format_as_sarif": ("r2morph.reporting.sarif_formatter", "format_as_sarif"),
    "SARIFArtifact": ("r2morph.reporting.sarif_schema", "SARIFArtifact"),
    "SARIFArtifactLocation": ("r2morph.reporting.sarif_schema_core", "SARIFArtifactLocation"),
    "SARIFCodeFlow": ("r2morph.reporting.sarif_schema_core", "SARIFCodeFlow"),
    "SARIFFileChange": ("r2morph.reporting.sarif_schema_core", "SARIFFileChange"),
    "SARIFFix": ("r2morph.reporting.sarif_schema_core", "SARIFFix"),
    "SARIFInvocation": ("r2morph.reporting.sarif_schema", "SARIFInvocation"),
    "SARIFLevel": ("r2morph.reporting.sarif_schema_core", "SARIFLevel"),
    "SARIFLocation": ("r2morph.reporting.sarif_schema_core", "SARIFLocation"),
    "SARIFLogicalLocation": ("r2morph.reporting.sarif_schema_core", "SARIFLogicalLocation"),
    "SARIFMessage": ("r2morph.reporting.sarif_schema_core", "SARIFMessage"),
    "SARIFNotification": ("r2morph.reporting.sarif_schema", "SARIFNotification"),
    "SARIFPhysicalLocation": ("r2morph.reporting.sarif_schema_core", "SARIFPhysicalLocation"),
    "SARIFRegion": ("r2morph.reporting.sarif_schema_core", "SARIFRegion"),
    "SARIFReplacement": ("r2morph.reporting.sarif_schema_core", "SARIFReplacement"),
    "SARIFReport": ("r2morph.reporting.sarif_schema", "SARIFReport"),
    "SARIFResult": ("r2morph.reporting.sarif_schema", "SARIFResult"),
    "SARIFRule": ("r2morph.reporting.sarif_schema", "SARIFRule"),
    "SARIFRun": ("r2morph.reporting.sarif_schema", "SARIFRun"),
    "SARIFSnippet": ("r2morph.reporting.sarif_schema_core", "SARIFSnippet"),
    "SARIFTaxon": ("r2morph.reporting.sarif_schema_core", "SARIFTaxon"),
    "SARIFTaxonReference": ("r2morph.reporting.sarif_schema_core", "SARIFTaxonReference"),
    "SARIFTaxonomy": ("r2morph.reporting.sarif_schema_core", "SARIFTaxonomy"),
    "SARIFThreadFlow": ("r2morph.reporting.sarif_schema_core", "SARIFThreadFlow"),
    "SARIFThreadFlowLocation": ("r2morph.reporting.sarif_schema_core", "SARIFThreadFlowLocation"),
    "SARIFTool": ("r2morph.reporting.sarif_schema", "SARIFTool"),
    "SARIFToolComponent": ("r2morph.reporting.sarif_schema", "SARIFToolComponent"),
    "EvidenceAggregator": ("r2morph.reporting.summary_aggregator_evidence", "EvidenceAggregator"),
    "SummaryAggregator": ("r2morph.reporting.summary_aggregator_summary", "SummaryAggregator"),
    "SymbolicAggregator": (
        "r2morph.reporting.summary_aggregator_symbolic_metrics",
        "SymbolicAggregator",
    ),
}

__all__: list[str] = []
__all__.extend(sorted(LAZY_EXPORTS))
